- .gitignore
- Makefile
Add dist make target to be consistent with other OpenSDS projects so
build artifacts can easily be collected in a consistent way across the
different deliverables.
> Add dist make target for build packaging

- Makefile
- api/Dockerfile
- backend/Dockerfile
- dataflow/Dockerfile
- datamover/Dockerfile
- docker-compose.yml
- docs/installation_and_testing.md
- s3/Dockerfile
This patch is proposed to remove some invalid characters in the name of docker images, so that we can push them into `docker.io` repository.
> Rename multi-cloud docker images

- docker-compose.yml
As default installing will pull the latest version of docker images, but that is not tested enough for us. So I specified the version we use for testing.
> Specify the version of docker images of kafka.

- api/pkg/s3/datastore/gcp/gcp.go
- api/pkg/s3/datastore/store.go
- backend/pkg/service/service.go
- backend/pkg/utils/constants/constants.go
- dataflow/pkg/model/dataflow_type.go
- dataflow/pkg/plan/plan.go
- dataflow/pkg/service.go
- datamover/pkg/drivers/https/migration.go
- datamover/pkg/gcp/s3/s3mover.go
New updated PR, this PR adds GCP adapter for S3 compatible interfaces and migration scenario from GCP to AWS also tested.
> Add GCP adapter for S3 compatible interfaces and added data mover interfaces for GCP backend

- api/pkg/s3/datastore/ibm/ibmcos.go
- api/pkg/s3/datastore/store.go
- backend/pkg/service/service.go
- dataflow/pkg/model/dataflow_type.go
- datamover/pkg/drivers/https/migration.go
- datamover/pkg/ibm/cos/cosmover.go
I added support for IBM COS, which is essentially a wrapper around AWS S3 (IBM COS APIs seem to be compatible, up to the point that the aws python cli can be used against an IBM COS instance). 
This is going to be the case until there is a functional go sdk for IBM COS (it is still a work in progress).
I tested the following:
- Uploading files to buckets in a COS instance.
- Adding multiple buckets.
- Migrating between buckets.
Thank you all for this awesome project.
> IBM cloud object storage support

- s3/pkg/datastore/yig/tests/utils_test.go
- s3/pkg/datastore/yig/utils/global_id.go
This PR adds a global id generator for yig storage driver. Because when create a multipart, we need a global unique id for the multipart upload, we can use that global id generator to generate this kind of 64-bit id.
The implementation of global id generator refers to the snowflake algo.
Also, tests are used to cover the function of global id generator.
```release-note
```
> add global id generator according to snowflake algo.

- docker-compose.yml
- s3/pkg/service/service.go
Signed-off-by: sunfch <sunspot0105@gmail.com>
1. Because sql statement in docker-compose.yml is not end with semicolon，database tables cannot be created at the beginning
2. fix wrong response body when create bucket successfully
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #701
```release-note
```
> Fix wrong response body and wrong sql statement in docker-compose.yml

- .gitignore
- docker-compose.yml
- s3/pkg/conf/tidb.sql
Support tidb data persistence
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #716
How to verify:
1. Do some operations which would write data to database, or you can write data base by sql.
```release-note
mysql> select * from users;
Empty set (0.00 sec)
mysql> insert into users (userid, bucketname) VALUES ("1", "TibdDataPersistenceTest");
Query OK, 1 row affected (0.00 sec)
mysql> select * from users;
+--------+-------------------------+
| userid | bucketname              |
+--------+-------------------------+
| 1      | TibdDataPersistenceTest |
+--------+-------------------------+
1 …
```
> Tidb data persistence

- datamover/pkg/drivers/https/migration.go
- datamover/pkg/drivers/https/prepare.go
- datamover/pkg/drivers/lifecycle/crosscloud_transition.go
- datamover/pkg/drivers/lifecycle/expiration.go
- datamover/pkg/drivers/lifecycle/incloud_transition.go
- datamover/pkg/drivers/lifecycle/lifecycle.go
- datamover/pkg/utils/data_type.go
- docker-compose.yml
- s3/pkg/service/object.go
This PR refactored migration function based on the CopyObject API provided OSDS S3 service, that means datamover do not need to migrate data by itself, then we do not need to maintain two copies of code for the same function. 
As those codes before used for migration data in datamover are removed, the progress update also need to do some change, so @Click2Cloud-Gamma please review the part about progress update.
```release-note
With this PR, objects less than PARTSIZE(16M as default) can be migrated, while objects bigger than this size …
```
> Support migration based on CopyObject API provided by OSDS S3 service

- s3/pkg/datastore/yig/factory.go
This PR fixes the problem of throwing yig backend exception when s3 stops.
The reason is that yig backend may not be initialized during s3 starts, when s3 stops, cfgWatcher of yig should be checked before calling its stop method.
```release-note
```
> fix the problem of yig crash when s3 stops.

- api/pkg/s3/bucketdelete.go
- api/pkg/s3/bucketget.go
- api/pkg/s3/bucketlifecycledelete.go
- api/pkg/s3/bucketlifecycleget.go
- api/pkg/s3/bucketlifecycleput.go
- api/pkg/s3/bucketput.go
- api/pkg/s3/objectdelete.go
- api/pkg/s3/objectget.go
- api/pkg/s3/service.go
- dataflow/pkg/scheduler/lifecycle/lifecycle_sched.go
When grpc server return error to grpc client, grpc client cannot get a response package except error, so the client cannot use the response package directly, otherwise, grpc client will crash. In this PR, we will make sure grpc client doesn't use response directly but check if it is null before using it.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #841 
Currently, if grpc server, like osds s3 service, want to return a business error to the grpc client, the grpc server need to return nil and a response package, but not error.
```release-note
```
> fix issue#841

- s3/pkg/datastore/ceph/ceph.go
- s3/pkg/datastore/gcp/gcp.go
- s3/pkg/datastore/init.go
- s3/pkg/utils/utils.go
This PR is to fix the bug that put object go GCS failed.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #848 
This PR does not include multipart upload for GCS, its traces by [issue#112](https://github.com/opensds/multi-cloud/issues/112)
```release-note
Put object and get object works for GCS:
```
> fix bug that put object go GCS failed

- s3/pkg/datastore/ceph/ceph.go
This PR is used to fix the bug that uploading object  failed while using ceph as backend.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #836 
```release-note
This PR does not fixed the issue that multipart uploading object failed when the object name has space in it, traced by [issue#851](https://github.com/opensds/multi-cloud/issues/851). 
The test report is as below:
Upload succeed:
Download succeed:
```
> fix bug that put object to ceph backend failed

- api/pkg/s3/objectcopy.go
- api/pkg/s3/objectget.go
- api/pkg/utils/utils.go
- docker-compose.yml
This PR is to fix the bug that downloading object failed.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #887 
The root cause of this bug is the way to calculate timeout is not correct, if object size is less than 5Bytes, then the timeout will be 0, that is not right. So, in this PR, the way to calculate timeout is modified.
```release-note
```
> fix the bug that downloading object failed

- api/pkg/s3/bucketdelete.go
This PR fix bug that response status code is 200 for delete request successfully
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #915
It should return 204 according to aws s3 api， and the url is https://docs.aws.amazon.com/AmazonS3/latest/API/API_DeleteBucket.html
```release-note
```
> return 204 when delete bucket successfully

- s3/pkg/conf/tidb.sql
- s3/pkg/datastore/yig/meta/db/tidb/multiparts.go
- s3/pkg/meta/db/drivers/tidb/multipart.go
This pr fix bug that we cannot resend part to s3 server with multipart mode
Old item should be deleted and new item is inserted into db, and repeated items in objectparts table are not allowed
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #916 
```release-note
```
> fix bug in multipart when resend part

- s3/pkg/datastore/aws/aws.go
- s3/pkg/datastore/ceph/ceph.go
- s3/pkg/datastore/gcp/gcp.go
>
This is to fix the issue that transition lifecycle rule does not work for GCP bucket to other backends.
Fixes [#1028 ](https://github.com/sodafoundation/multi-cloud/issues/1028)
> /kind TESTED
The transition from STANDARD GCP to STANDARD_IA OBS.
1. Upload an object to a bucket with GCP as it's default backend.
2. Create a lifecycle rule to transition from STANDARD GCP to STANDARD_IA OBS:
3. …
> Fix the issue that transition from gcp to other backend failed.

- contrib/datastore/file/gcp/constants.go
- contrib/datastore/file/gcp/gcp.go
**What this PR does / why we need it**: This PR is needed to support File Share Creation for GCP cloud backend.
Fixes #1076 
> /kind TESTED
The following testing is done for Create File Share API for GCP cloud backend:
**Register a Backend**
Example 1: Registering an Azure Backend for File Share
POST http://192.168.20.162:8089/v1/94b280022d0c4401bcf3b0ea85870519/backends
Request:
```
{
"name": "gcp-backend-file",
"type": "gcp-file",
"Region": "<project_id>",
"Access": "<access_key>",
"Security": "<secret_key>"
}
```
Response:
```
{
"id": "5f66397740852a0001bcc3f7",
"tenantId": "94b280022d0c4401bcf3b0ea85870519",
"userId": "558057c4256545bd8a307c37464003c9",
"name": …
```
> [GCP FileShare Support]  Implement Create Fileshare API for GCP Fileshare Driver

- file/pkg/service/service.go
**What this PR does / why we need it**: This PR will fix for nil pointer derefence for FileShare resouces in the service layer for fileshare updation
Fixes #1106 
> /kind TESTED
> [GCP FileShare Support] Fix for Invalid memory address or nil pointer dereference for GCP Fileshare Updation

- s3/pkg/service/service.go
- s3/pkg/utils/utils.go
>
/kind bug fix
> /kind design
Archived object storage tier was not properly displayed. 
*Note: SODA maps storage classes into three tiers. TIER1, TIER99, TIER999 i.e. STANDARD, STANDARD_IS and GLACIER*
Fixes #1203 
/kind TESTED
Currently the storage class is changed only for archival. Other storage class (non-archival) need to be properly tested and then modified. Also, …
> Fix GCP Archived object type display

- api/pkg/s3/service.go
- backend/pkg/service/service.go
- s3/pkg/service/bucket.go
- s3/pkg/service/object.go
- s3/pkg/utils/utils.go
This PR is about removing Access and Security crednetials details from log. WHile creating/deleting or doing any operation on bucket, Access and Security key of users were visible in logs. So, need to remove due to security violance issue.
>
> /kind design
Fixes #
> /kind TESTED
**Test …
> Removing credentials from log

- K8s/api-deployment.yaml
- K8s/file-deployment.yaml
- K8s/k8s-deploy.sh
- K8s/mongo-service-0.yaml
- K8s/mongo-service-1.yaml
- K8s/mongo-service-2.yaml
- K8s/s3api-deployment.yaml
- K8s/soda-secret.yaml
>
> /kind design
Fixes #1230 
kind TESTED
> Issue 1230-1 : Use secrets in Pod Yamls.

- api/pkg/backend/service.go
#932
>
/kind bug fix
> /kind design
This will modify response of the GET Backend API with invalid ID, DELETE Backend API with invalid ID and UPDATE Backend API with invalid ID. 
Now the response is 500. The modified response will be 404 with proper error message.
Error MSG : Invalid backend id: <backend Id provided>
Fixes #932 …
> 500 Internal Error for GET, PUT, DELETE Backend for a non existing backend #932

- api/pkg/dataflow/service.go
kind bug fix
While using postman api, when the get jobs is hit, job number which does not exist in the system throws a 500 internal server error message which is wrong. When a job does not exist in the system it will simply throw an 404 error and show message as "Job <id> does not exist in the system"
Fixes #https://github.com/sodafoundation/multi-cloud/issues/938
/kind TESTED
**Special …
> Code changed to show correct status from postman when job does not exist

- .github/workflows/ci.yml
Why this PR:
>
> /kind design
Fixes #
> /kind TESTED
* All services are up and running, with go 1.17.9
-->
>  Updating go version 1.13.x to 1.17.9 ci.yml

- backend/pkg/db/drivers/mongo/mongo.go
- datamover/pkg/db/drivers/mongo/mongo.go
/kind bug fix
1) In Strato functional testing yesterday discovered that after creating migration plans. Even though object is migrated from src to the target bucket the status of the migration plan doesn't reflect the same due to an internal issue in code related to the database update
2) In Storage Service Plan mode of installation backends was getting listed as SSPs
Fixes #
/kind TESTED
Creating a service plan now lists the service plan instead of the previous backends 
Creating bucket with SSP is now working
- Migration from AWS to GCP
Status and number of objects migrated is correct
Object is also present in the target bucket 
- Migration from …
> Starto migration status not updating fix and Backend listing as SSP fix

- backend/pkg/db/drivers/mongo/mongo.go
/kind bug fix
Tier Update i.e. add/delete backend/tenant was not happening in the mongo database and backend modification was failing.
This PR fixes the DB update operation. Now, the tier is being updated as intended and modify backend is also working.
Fixes #1362
> Fix for update tier in SSP and modify backend

- installer/ansible/group_vars/common.yml
- installer/ansible/group_vars/gelato-ha.yml
- installer/ansible/roles/auth-installer/tasks/main.yml
- installer/ansible/site.yml
This PR contains some minor changes in multi-cloud ansible installer which are required for integration with common installer. 
/kind TESTED
Installation successfully completed using common installer:
All multi-cloud services up and running:
Dashboard running with multi-cloud enabled:
> Refactoring multi-cloud installer for integration with common installer

- installer/ansible/roles/auth-installer/tasks/main.yml
- installer/ansible/roles/gelato-installer/tasks/main.yml
/kind bug fix
checking for keystone installation requires docker-py package. Hence, it should be installed before the task where checking for keystone installation happens.
> install docker-py package before checking for keystone installation

- api/pkg/metadata/service.go
- metadata/pkg/constants/Constants.go
- metadata/pkg/drivers/aws/aws.go
- metadata/pkg/query-manager/translator.go
- metadata/pkg/query-manager/validator.go
- metadata/pkg/service/service.go
- region name coming as bucket name fix
- removing query result from log
- fixing msg when type is valid and region not specified
- converting bucketSizeOperator  and objectSizeOperator to camelCase
- store objects even though some api failed for object level
- supporting caseinsensitive cloud type and coverting to lowercase internally
Fixes #
> /kind TESTED
- region name coming as bucket name fix
- converting bucketSizeOperator  and objectSizeOperator to camelCase
- removing query results from the log
- fixing msg when type is valid and region not specified
- supporting case-insensitive cloud type and converting to lowercase …
> Issuefix for metadata manager fixes

- metadata/pkg/drivers/aws/aws.go
Currently metadata collection is being done for all the buckets irrespective of the region. But now as per the requirement, only buckets associated with the backend region need to be considered for metadata collection. This PR updates the aws driver for fulfilling the requirement.
> aws driver updated to collect bucket metadata associated with backend region only
