api/pkg/s3/datastore/store.go

add  feature of object download

add  feature of object download

---

api/pkg/s3/completemultipartupload.go
api/pkg/s3/datastore/aws/aws.go
api/pkg/s3/datastore/hws/hws.go
api/pkg/s3/datastore/store.go
api/pkg/s3/objectput.go

Get the multi-part upalod object size from cloud.

Fixed multi-part updload has no size value issue

---

api/pkg/s3/datastore/aws/aws.go
api/pkg/s3/objectput.go

add interface of upload

---

backend/pkg/utils/constants/constants.go

change sotrage backend type name

change sotrage backend type name

---

openapi-spec/swagger.yaml

add api spec in swaager format

add api spec in swaager format

---

api/pkg/s3/objectget.go

Fxied download object formate error

Fxied download object formate error

---

api/pkg/s3/datastore/aws/aws.go

Fixed multi-part upload keys error

Fixed multi-part upload keys error

---

api/pkg/s3/datastore/aws/aws.go
api/pkg/s3/datastore/azure/azure.go
api/pkg/s3/datastore/store.go
api/pkg/s3/objectget.go
docker-compose.yml

fix the azure  download bug

---

api/pkg/s3/datastore/hws/hws.go
api/pkg/s3/objectdelete.go
api/pkg/s3/objectput.go
api/pkg/s3/service.go
s3/pkg/service.go

add new feature of objectput

---

api/pkg/s3/objectdelete.go
api/pkg/s3/service.go

fix the delete bug

---

api/pkg/s3/abortmultipartupload.go
api/pkg/s3/completemultipartupload.go
api/pkg/s3/datastore/azure/azure.go
api/pkg/s3/datastore/hws/hws.go
api/pkg/s3/objectdelete.go
api/pkg/s3/objectget.go
api/pkg/s3/objectput.go
api/pkg/s3/service.go
api/pkg/s3/uploadpart.go

fix the download bug

---

dataflow/pkg/plan/plan.go
dataflow/pkg/scheduler/trigger/crontrigger/crontrigger.go

open the commented code

---

api/pkg/s3/completemultipartupload.go
api/pkg/s3/datastore/aws/aws.go
api/pkg/s3/objectget.go
api/pkg/s3/objectput.go
datamover/pkg/drivers/https/migration.go
s3/pkg/service.go
s3/proto/s3.micro.go

fix the upload bugs

---

api/pkg/s3/datastore/azure/azure.go

add new returns of azure uploadPart

add new returns of azure uploadPart

---

api/pkg/s3/datastore/aws/aws.go
api/pkg/s3/datastore/azure/azure.go
api/pkg/s3/uploadpart.go

fix the size bug

---

api/pkg/s3/datastore/aws/aws.go
api/pkg/s3/multipartuploadinit.go
api/pkg/s3/uploadpart.go

fix the aws bug

---

api/pkg/s3/multipartuploadinit.go

fix the multipartuploadinit bug

fix the multipartuploadinit bug

---

api/pkg/s3/datastore/aws/aws.go
api/pkg/s3/datastore/azure/azure.go
api/pkg/s3/datastore/hws/hws.go
api/pkg/s3/datastore/store.go
api/pkg/s3/objectget.go
api/pkg/s3/uploadpart.go

add mutipartdownload function

---

api/pkg/s3/bucketput.go
api/pkg/s3/datastore/store.go
api/pkg/s3/service.go
s3/pkg/exception/exception.go

add the NoSuchType exception

---

docs/installation_and_testing.md

Solve: #61 
- Change the back-end type from `aws` to `aws-s3`

Update installation_and_testing document

---

api/cmd/main.go
api/pkg/filters/auth/auth.go
api/pkg/filters/auth/keystone.go
docker-compose.yml

multi-cloud deploy need

---

script/bootstrap.sh

Add bootstrap script for multi-cloud, so user can deploy the multi-cloud with one step.

add bootstrap script for multi-cloud

---

api/pkg/s3/datastore/ceph/ceph.go
dataflow/pkg/model/dataflow_type.go
dataflow/pkg/plan/plan.go
dataflow/pkg/service.go
datamover/pkg/ceph/s3/s3mover.go
datamover/pkg/drivers/https/migration.go
datamover/pkg/utils/data_type.go

@xing-yang As discussed this is tested for AWS to Ceph and vice-versa scenario for files ranging upto 2.4GB.

Add data mover interfaces for ceph backend

---

api/pkg/s3/datastore/hws/hws.go
api/pkg/s3/routeobjectdelete.go
api/pkg/s3/router.go

fix the abortmultipartupload method bug

fix the abortmultipartupload method bug

---

script/bootstrap.sh

1. modified the configuration file env format

modified the configuration file env format

---

Gopkg.lock
api/cmd/main.go
api/pkg/filters/auth/keystone.go
api/pkg/filters/signature/credentials/credential.go
api/pkg/filters/signature/credentials/credential_test.go
api/pkg/filters/signature/credentials/keystonecredentials/provider.go
api/pkg/filters/signature/credentials/keystonecredentials/provider_test.go
api/pkg/filters/signature/signer/signature.go
api/pkg/filters/signature/signer/signature_test.go
api/pkg/utils/constants/constants.go
testhelper/gophercloudclient/mock.go
testhelper/http_responses.go
vendor/github.com/gophercloud/gophercloud/auth_options.go
vendor/github.com/gophercloud/gophercloud/auth_result.go
vendor/github.com/gophercloud/gophercloud/doc.go
vendor/github.com/gophercloud/gophercloud/errors.go
vendor/github.com/gophercloud/gophercloud/openstack/auth_env.go
vendor/github.com/gophercloud/gophercloud/openstack/client.go
vendor/github.com/gophercloud/gophercloud/openstack/identity/v2/tenants/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/identity/v2/tokens/results.go
vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/credentials/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/credentials/results.go
vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/credentials/urls.go
vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/tokens/results.go
vendor/github.com/gophercloud/gophercloud/provider_client.go
vendor/github.com/gophercloud/gophercloud/service_client.go

Support keystone credential retrieval mechanism and provide signing and authenticating requests to manage multi-cloud APIs.

Provide Support for Multi-Cloud AK/SK Management

---

api/cmd/main.go

#110 
* Apply Webservice auth filter.
* Remove auth filter for s3 interface.

Add auth service filter and remove auth token for S3 Interface

---

Makefile

Optimize the compilation time, now the module without code modification will not be compiled anymore, so the total compile time will decrease extremely most of the time.

Optimize compilation time.

---

docker-compose.yml

add  docker-compose.yml bali tags

add  docker-compose.yml bali tags

---

api/cmd/main.go

we need fix the auth bug
the bugs is remained for a long time . it is caused by Himanshu Varshney. I fix the auth bug

fix auth bug

---

dataflow/pkg/scheduler/lifecycle/lifecycle_sched.go

fixes #141 [https://github.com/opensds/multi-cloud/issues/141](url)

fixes Issue141

---

backend/pkg/service/service.go

fixes #139 [https://github.com/opensds/multi-cloud/issues/139](url)

fix bug of issue139

---

api/pkg/backend/service.go
backend/pkg/service/service.go

**Which issue this PR fixes**
fixes issue [https://github.com/opensds/multi-cloud/issues/139](https://github.com/opensds/multi-cloud/issues/139)

fixes issue#139

---

api/pkg/backend/service.go
backend/pkg/service/service.go

Merge development into master branch to publish Capri RC-02

---

api/pkg/backend/service.go
s3/pkg/service.go

fixes [https://github.com/opensds/multi-cloud/issues/149](https://github.com/opensds/multi-cloud/issues/149)

clear sensative information for lifecycle and remove tier99 and tier999 support for GCP

---

api/pkg/s3/bucketlifecycleput.go

This is the update in PUT lifecycle API 
```release-note
```

PUT bucket lifecycle API update

---

dataflow/pkg/scheduler/lifecycle/lifecycle_sched.go
dataflow/pkg/utils/utils.go

Fix some serious issue
```release-note
```

Merge Development to Master

---

api/cmd/main.go

1. remove duplicate code which will cause panic issue in noauth mode
```release-note
```

remove duplicate code

---

api/Autobuildfile
api/hooks/pre_build
backend/Autobuildfile
backend/hooks/pre_build
dataflow/Autobuildfile
dataflow/hooks/pre_build
datamover/Autobuildfile
datamover/hooks/pre_build
s3/Autobuildfile
s3/hooks/pre_build

add autobuild files, to autobuild docker images
```release-note
```

add autobuild files

---

docker-compose.yml
s3/pkg/conf/s3.toml
s3/pkg/conf/tidb.sql

Signed-off-by: sunfch <sunspot0105@gmail.com>
change database name s3
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #707
```release-note
```

Change database name s3

---

s3/pkg/datastore/yig/storage/gc.go
s3/pkg/meta/types/bucket.go

fix the bug that cannot creating bucket

---

api/pkg/s3/bucketget.go
api/pkg/s3/bucketlifecycleput.go
api/pkg/s3/bucketversioningput.go
api/pkg/s3/listbuckets.go
api/pkg/s3/objectacl.go
api/pkg/s3/objectcopy.go
api/pkg/s3/objectget.go
api/pkg/s3/routbuckethead.go
api/pkg/s3/routeobjecthead.go
api/pkg/s3/service.go
s3/pkg/meta/db/drivers/tidb/bucket.go
s3/pkg/meta/db/drivers/tidb/object.go
s3/pkg/service/bucket.go
s3/pkg/service/object.go
s3/pkg/service/service.go

This PR is to provide the basic ability of HEAD object&bucket.
```release-note
SSE setting is not included for HEAD object yet.
```

support to head bucket&object

---

api/pkg/s3/listbuckets.go
s3/pkg/meta/db/drivers/tidb/bucket.go

This fixes a nil pointer bug when the bucket does NOT have any SSE settings
```release-note
```

bug fix to avoid nil pointer

---

s3/pkg/meta/db/drivers/tidb/bucket.go

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #789 
```release-note
```

fix bug, issue789

---

s3/pkg/datastore/azure/azure.go
s3/pkg/meta/db/drivers/tidb/bucket.go
s3/pkg/service/object.go

bug fix for migration from azure blob failed.

---

s3/pkg/datastore/azure/azure.go
s3/pkg/datastore/yig/factory.go
s3/pkg/meta/db/drivers/tidb/bucket.go
s3/pkg/service/object.go

**What this PR does / why we need it**: Adding changes from development to master for Object migration 
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes # Based upon dev testing
```release-note
```

Merge development branch to master for RC2. 

---

api/pkg/s3/abortmultipartupload.go
api/pkg/s3/bucketdelete.go
api/pkg/s3/bucketget.go
api/pkg/s3/bucketlifecycledelete.go
api/pkg/s3/bucketlifecycleget.go
api/pkg/s3/bucketlifecycleput.go
api/pkg/s3/bucketput.go
api/pkg/s3/completemultipartupload.go
api/pkg/s3/listbuckets.go
api/pkg/s3/multipartuploadinit.go
api/pkg/s3/objectcopy.go
api/pkg/s3/objectdelete.go
api/pkg/s3/uploadpart.go

Signed-off-by: sunfch <sunspot0105@gmail.com>
fix bug that when S3 gprc server return error API grpc client crashed
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #810
```release-note
```

Fix api crash when grpc server return error

---

api/pkg/s3/bucketput.go

Fix bug that null acl in bucket table when create bucket
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #820 
```release-note
```

Fix bug that null acl in bucket table

---

api/pkg/s3/objectcopy.go
api/pkg/s3/objectget.go
datamover/pkg/drivers/https/migration.go
datamover/pkg/drivers/lifecycle/crosscloud_transition.go
docker-compose.yml
s3/pkg/datastore/aws/aws.go
s3/pkg/datastore/azure/azure.go
s3/pkg/datastore/gcp/gcp.go
s3/pkg/meta/object.go
s3/pkg/service/multipart.go
s3/pkg/service/object.go

fix bug in issue #828

---

api/pkg/s3/objectput.go

Client cannot get successful response when put object failed in backend.  I have add the check for error code and the bug is fixed
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #846 
```release-note
```

Add error code check when put object

---

api/pkg/s3/multipartuploadinit.go

support to choose a specific backend when init multipart
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #761
```release-note
```

Support to choose a specific backend when init multipart upload

---

s3/pkg/conf/tidb.sql

This PR is used to fix issue #868 
Test result is below.
Check object before create lifecycle rule:
Create cross-cloud transition lifecycle rule:
Wait until the rule takes effect and check the result:
```release-note
```

fix bug described in issue#868

---

s3/pkg/meta/db/drivers/tidb/bucket.go
s3/pkg/service/object.go

fix for #869 
#869 
```
This also adds a fix to delete SSE settings on bucket delete
```

fix fo r#869

---

s3/pkg/meta/db/db.go
s3/pkg/meta/db/drivers/tidb/bucket.go
s3/pkg/service/bucket.go
s3/pkg/service/service.go

This is a fix for excluding versioning in Daito release, no insertion or updation in bucket_versionopts table 
```release-note
```

Fix for excluding versioning in Daito

---

Makefile
docker-compose.yml
s3/Dockerfile
s3/initdb.sh
s3/pkg/conf/tidb.sql

this fixes issue 843
#843 
```
Remove the mysql container. Install the mysql client in s3 container. Add a script in the s3 container to connect to tidb and initialize it (with a retry mechanism, to retry 5 times, 2 seconds apart), then start the s3 process
```

fix for 843

---

api/cmd/main.go
api/pkg/filters/signature/auth-handler.go
api/pkg/filters/signature/credentials/credential.go
api/pkg/filters/signature/post-policy.go
api/pkg/filters/signature/postpolicyform.go
api/pkg/filters/signature/signer/signature.go
api/pkg/filters/signature/streaming-signature-v4.go
api/pkg/filters/signature/streaming-signature-v4_test.go
api/pkg/filters/signature/v2.go
api/pkg/filters/signature/v4-parser.go
api/pkg/filters/signature/v4-utils.go
api/pkg/filters/signature/v4.go
api/pkg/filters/signature/verify-reader.go
docker-compose.yml

This PR is the first PR to make multi-cloud be compatible with AWS S3. Two things include in this PR:
1. Seperate s3 APIs from other APIs. After this change, there will run two api containers, one for s3 APIs, one for other APIs. 
2. Modificate authentication algorithm and make it support auth v2/v4.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #893 
```release-note
This PR just fix the URL and authentification issues, but not make sure all S3 APIs be compatible with AWS S3. We will do AWS S3 compatible test next, and raise new PRs if needed.
```

Fix the URL and authentication issue which is not aws s3 compatible

---

api/pkg/s3/handler-utils.go
api/pkg/s3/multipartuploadinit.go
api/pkg/s3/objectcopy.go
api/pkg/s3/objectpost.go
api/pkg/s3/objectput.go
s3/pkg/service/object.go

Signed-off-by: sunfch <sunspot0105@gmail.com>
1. extract metadata and store them with object in post object request
2. return correct redirect url in response
3. Verify the signature for the POST request
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #919 
```release-note
```

fix bug for object post

---

README.md

Updated the ReadMe as per SODA ReadMe template and provided all the latest SODA specific information pertaining to this project
ReadMe was out-dated. Hence this PR will provide an updated ReadMe for the project
NA
NA
NA

Project ReadMe updated

---

docker-compose.yml

>
kind bug fix
To fix issue #957 
Fixes #
kind TESTED

To retain mongodb data

---

api/cmd/main.go

>
> /kind design
It's used to fix the issue that backend and dataflow related APIs does not work with /v1 in the request url.
Fixes #
> /kind TESTED

fix the bug that backends and dataflow APIs not work with v1 in the url.

---

s3/pkg/datastore/alibaba/alibaba.go

>
kind bug fix
> /kind design
This will enable user to create folder using soda dashboard ( #1044)  &  also fixes issue #1045 
Fixes for #1044 and #1045 
TESTED
https://drive.google.com/file/d/1ytg186t-kMLXtJaUilLfJWM_OBjtlIiw/view?usp=sharing

patch to fix alibaba multipart(lifecycle) and folder issue

---

Makefile
docker-compose.yml
docs/installation_and_testing.md

>
kind new feature
> /kind design
Rename the image name from opensdsio to sodafoundation
Fixes #1027 
kind TESTED
Here is the docker ps
```
root@aks:~/gopath/src/github.com/sodafoundation/multi-cloud# docker ps |grep multi-cloud
df5fbb76ef67        sodafoundation/multi-cloud-datamover …
```

Change name of the images from opensdsio to sodafoundation

---

openapi-spec/swagger.yaml

**What this PR does / why we need it**: This PR is to update the Swagger for FileShare APIs
Fixes #1048 
> /kind TESTED

Swagger Update for FileShare

---

openapi-spec/swagger.yaml

Update api spec swagger file with API '/v1/{tenantId}/volumes'
NA
NA
NA

Update swagger for block volumes APIs

---

Makefile

/kind new feature
Added the multi cloud file service to the build location
Fixes #
/kind NOT-TESTED

Added multi cloud file service to the build

---

.travis.yml

>
Adding code coverage for pakages with tests. 
Fixes #
NA

Add Code coverage for pkg with tests

---

docs/installation_and_testing.md

/kind bug fix
This PR fixes GO version mismatch in the documentation of Multi-cloud Local Cluster Installation and Testing
Fixes # 
https://github.com/sodafoundation/multi-cloud/issues/1069
Documentation fix

Documentation issue fix  in Multi-cloud Local Cluster Installation and Testing

---

block/pkg/service/service.go

**What this PR does / why we need it**: This PR will fix for nil pointer derefence for Block resources in the service layer for block Creation/Updation
Fixes #1113 #1114 
> /kind TESTED

[AWS Block Service] Bug-Fix: Added check for nil Volume return for Creation/Updation

---

contrib/datastore/block/aws/aws.go

**What this PR does / why we need it**: This PR is to correctly return the Error Message from Driver layer to Service layer
**Which issue(s) this PR fixes**: #1116 
Fixes #
> /kind TESTED

[AWS Block Support] Fix to Update Error return Typos for failed Volume operation at Backend

---

openapi-spec/swagger.yaml

**What this PR does / why we need it**: To provide latest API specification for Block Service
Fixes #1121 
> /kind TESTED

[Multi-Cloud API Documentation] Update Swagger for Block CRUD APIs

---

CHANGELOG/CHANGELOG-v1.0.0.md

>
/kind new feature
> /kind design
Changelog for v1.1.0 release 
Fixes #
> /kind TESTED

Adding changelog for v1.1.0 release

---

api/pkg/block/service.go
backend/pkg/service/service.go
backend/pkg/utils/constants/constants.go
block/pkg/service/service.go
block/pkg/service/service_test.go
contrib/datastore/block/common/constants.go
contrib/datastore/block/hpc/factory.go
contrib/datastore/block/hpc/hpc.go
contrib/datastore/init.go
go.mod
go.sum

>
/kind new feature
> /kind design
Adding support for HPC EVS Disk CRUD Operation.
Using Huawecloud golang SDK
Fixes #1136 #1137 #1138 #1139 
/kind TESTED
**Register backend**
POST: http://192.168.20.163:8089/v1/94b280022d0c4401bcf3b0ea85870519/backends
Request: (project_name is the region alias …

Adding support for Huawei Public Cloud EVS

---

api/pkg/backend/service.go

when a create backend request is sent, type of the backend is to be verified to proceed.
Fixes #1107 
> /kind TESTED
when an invalid backend type is given:
When a valid backend type is given:

Fix for invalid backend type 

---

openapi-spec/swagger.yaml

/kind new feature
This is the swagger update for Object archival and restore APIs
Fixes #
/kind TESTED

Swagger API spec update for archival and restore

---

s3/pkg/datastore/aws/aws.go
s3/pkg/datastore/azure/azure.go
s3/pkg/datastore/gcp/gcp.go
s3/pkg/datastore/huawei/huawei.go

This PR includes
1. CRUD  bucket implementation of huawei cloud and validation of credentials of aws and azure backends
2. Includes multipart object upload of aws,azure, huawei cloud.
Given fake access key:
Showing error as **invalid credentials**:

Backend check changes and huawei CRUD

---

docker-compose.yml

Issue Fix PR 
>
kind bug fix
> /kind design
Fixes the order of service start up so that services do not fail. 
Fixes  
> /kind TESTED

Fix service dependency in multi-cloud

---

examples/multi-cloud.conf

/kind bug fix
The PR updates default log level from debug to info
Fixes #1242
> /kind TESTED
/kind TESTED
NA

update default log level to info

---

s3/pkg/datastore/alibaba/alibaba.go
s3/pkg/service/bucket.go

This PR has implementation of bucket management for alibaba cloud. The code is tested with all bucket operation like, create, delete, upload, multi-part upload, migration etc.
>
> /kind design
Fixes #1249  
> /kind TESTED
1. Register  backend
2. Create bucket
3. Upload Object …

Bucket management support for alibaba cloud

---

api/pkg/s3/bucketput.go
api/pkg/s3/service.go

1. User/Admin can create bucket using tiers. Now, Admin can hide the backends details from users.
2. This PR has only scope for Admin. i.e, Admin only can create bucket from tiers.
> /kind design
Fixes #1267 
> /kind TESTED
1. Create Backend:
POST http://192.168.29.183:8089/v1/94b280022d0c4401bcf3b0ea85870519/backends
**Request Body:**
{
"Name": "admin-aws1",
"Type": "aws-s3",
"Region": …

Bucket creation using tier

---

backend/pkg/service/service_test.go
testutils/backend/collection/data.go

>kind enhancement
This PR contains Unit Testing for tiering functions added in PR #1269 
Fixes #
> /kind TESTED

Unit Testing for CRUD tier functions

---

api/pkg/backend/service.go

kind bug fix
This PR is to change the word tier to service plan in error messages and success messages in API responses 
Fixes #1280 
kind TESTED

Change of  the word Tier to Service Plan from all success and error messages in the API responses

---

api/pkg/s3/objectput.go

This PR for fixing a issue when SSP is enabled:
* When there are multiple backends in a SSP and buckets are created on different backends of SSP.
* Internal logic, was selecting the random backenId for bucket. But it should pick only those backend in which buckets are created.
* This PR will select only that backends in which buckets are crated and based on backend Type, storageClass will be filled for archiving.
>
> /kind design
Fixes #1284 
**Test …

Fixing issue for Archive if, multiple backends in SSP

---

openapi-spec/swagger.yaml

Storage Service Plan is new feature and it will be available from J-release. 
So this PR is for swagger file for SSP feature supported API. 
> /kind design
Fixes #
> /kind TESTED
1. All SSP API's
2. POST SSP API
3. PUT SSP API
4. GET SSP API
5. DELETE SSP API

Swagger Update for SSP CRUD

---

openapi-spec/swagger.yaml

Adds AKSK Swagger API documentation
>
kind documentation
Adds AKSK Swagger API documentation
Fixes #
kind TESTED

Add aksk swagger file 

---

aksk/pkg/iam/driver/keystone/keystone.go
aksk/pkg/service/service.go
api/pkg/aksk/service.go
api/pkg/backend/service.go
api/pkg/utils/utils.go

>
- The PR adds validations for project_id, and user_id . 
- AKSK will be created for valid projects and users.
- added checks for blank and invalid projectId and userId. 
Fixes #1287 
kind TESTED

Add validation for projectId, userId

---

api/pkg/filters/auth/keystone.go

>
kind bug fix
> /kind design
This PR solves a bug where admin can now be able to list down all the buckets(Admin+ user)
Fixes #1297 
kind TESTED
**User-u3 bucket list:**
**Admin buckets and u3 buckets are listed down:**

[SSP]Admin to list all buckets

---

.github/workflows/ci.yml

/kind bug fix
To fix the issue of deprecated Ubuntu 16.04 runner, adding the Ubutnu 18 runner to test CI.
Due to [deprecation of support](https://github.blog/changelog/2021-04-29-github-actions-ubuntu-16-04-lts-virtual-environment-will-be-removed-on-september-20-2021/) removed the Ubuntu 16.04 run from the GitHub Actions.
Fixes #
> /kind TESTED

Added Ubuntu1804 runner to test CI. Removed Ubuntu 16.04 

---

api/pkg/backend/service.go

This is fix for: #1311 
>
> /kind design
Fixes #
> /kind TESTED
1. 
2. 

Fixing Issues: Validation of tenant in ListTiers #1311

---

README.md

>
> /kind design
Fixes #1325 
> /kind TESTED

added new release name to README.md

---

api/pkg/s3/service.go
backend/pkg/db/drivers/mongo/mongo.go

Update backends to SSP is failing
>
> /kind design
Fixes #
> /kind TESTED

Fix for update ssp backends

---

installer/ansible/group_vars/common.yml

release version update in installer
Fixes #

release version update in installer

---

installer/README.md
installer/ansible/group_vars/common.yml

/kind documentation
* Updated README to add instructions to use multi-cloud with dashboard. 
* Removed an unused variable in ansible installer common.yml file.

Updated README.md, removed unused variable

---

installer/README.md
installer/install_dependencies.sh

Shifted some dependency installation steps from README file to install_dependencies.sh

shifted dependencies installation steps from README to install_dependencies.sh

---

installer/ansible/group_vars/common.yml

Update the release version of starto:
1. v1.7.0 --> v1.8.0
>
> /kind design
Fixes #
> /kind TESTED

Update the release version

---

go.sum
vendor/github.com/journeymidnight/radoshttpd/rados/conn.go
vendor/github.com/journeymidnight/radoshttpd/rados/pool.go
vendor/github.com/journeymidnight/radoshttpd/rados/striper.go
vendor/modules.txt

Since we are tracking the vendor files with our version control those also need to updated incase of dependency change which was not done for radoshttp
Fixes #
> /kind TESTED

vendor files updated using "go mod vendor"

---

api/pkg/metadata/service.go
metadata/pkg/model/model.go
metadata/pkg/query-manager/validator.go
metadata/pkg/service/service.go

Minorfixes - Cleanup log directives and make Validation err errMsg accessible outside pkgs

---

installer/ansible/roles/gelato-installer/tasks/main.yml

/kind bug fix
This PR fixes the issue of SODA Strato not being installed.
Fixes #1421 
/kind TESTED

Fixed metadata image tag not being replaced in the installer issue.

---

installer/README.md

>
> /kind design
Fixes #
> /kind TESTED

Updating demo video to installation guide
